# 异步编程：Promise

JavaScript作为浏览器脚本语言，主要用途是响应用户的交互操作DOM，这决定了它只能是**单线程**

## JS的两种编程思想

 * 异步: 不进入主线程，而进入任务队列的任务。当主线程任务执行完毕后，任务队列才通知主线程，请求执行任务，该任务才会进入主线程执行。
 * 同步: 只有前一个任务执行完毕，才能执行后一个任务

回调地狱的负面作用：

* 代码臃肿
* 可读性差
* 耦合度过高, 可维护性差
* 代码复用性差
* 只能在回调里处理异常

## Promise 是异步编程解决方案

Promise的两个特点
 - 对象的状态不受外界影响。 `pending` 、 `fulfilled` 、 `rejected`
 - 一旦状态改变，就不会再变，任何时候都可以得到这个结果  

Promise常用方法的polyfill示例ß

```js 
//构造函数
function Promise(executor) {//executor执行器

    let that = this;
    that.status = "pending";
    that.success = undefined;
    that.err = undefined;
    that.fulFillEventLists = [];
    that.rejectEventLists = [];
    function resolve(val) {
        if (that.status == "pending") {
            that.success = val;
            that.status = "fulfilled";
            setTimeout(() => {
                that.fulFillEventLists.map(fn => { fn() });
            }, 1000)
        }
    }
    function reject(err) {
        if (that.status == "pending") {
            that.err = err;
            that.status = "rejected";
            setTimeout(() => {
                that.rejectEventLists.map(fn => { fn() });
            }, 1000)
        }
    }
    try {
        executor(resolve, reject);
    } catch (e) {
        reject(e)
    }

}

``` 

#### `then` 方法

Promise的实例具有 `then` 方法， `then` 方法的第一个参数是 `resolved` 状态的回调函数，第二个参数（可选）是 `rejected` 状态的回调函数。 `then` 方法返回一个新的 `Promise` 实例。
```js
//实现then方法
Promise.prototype.then = (onFulfilled, onRejected) => {
    //回调函数检测，设置其默认值
    onFilfilled = typeof onFulfilled === "function" ? onFulfilled : val => val;
    onRejected = typeof onReject === "function" ? onRejected : err => { throw err }
    const self = this;
    return Promise((resolve, reject) => {
        function handle(callback, value) {
            try {
                const result = callback(value);
                if (result instanceof Promise) {
                    result.then(resolve, reject);
                } else {
                    resolve(result);
                }
            } catch (e) {
                reject(e);
            }
        }
        if (self.status == "fulfilled") {
            setTimeout(() => {
                handle(onFulfilled, self.success)
            }, 1000)
        } else if (self.status == "rejected") {
            setTimeout(() => {
                handle(onRejected, self.err)
            }, 1000)
        } else if (self.status == "pending") {
            self.fullFillEventLists.push(() => { handle(onFulfilled, self.success) });
            self.rejectEventLists.push(() => { handle(onFullfilled, self.err) });
        }
    })
}
```

#### `catch` 方法

`catch()` 方法用于指定发生错误时的回调函数，返回的还是一个Promise对象。

> 与 `try/catch` 代码块不同的是，没有使用 `catch` 方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，不会有任何反应。

``` js
//实现catch方法
Promise.prototype.catch = (onRejected) => {
    return this.then(undefined, onRejected)
}
```

#### `finally` 方法

`finally` 方法的回调函数不接受任何参数，与前置的Promise状态无关，不依赖Promise的执行结果

``` js
Promise.prototype.finally = function(callback) {
    let P = this.constructor;
    return this.then(
        value => P.resolve(callback()).then(() => value),
        reason => P.resolve(callback()).then(() => {
            throw reason
        }));
}
```
